name: integration
on:
  push:
    # branches:
    # - master
jobs:
  test:
    runs-on: macOS-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v2
    - name: install
      run: |
        GOBIN=$HOME/bin make install
        echo "$HOME/bin" >> "$GITHUB_PATH"
        brew install mercurial fossil bazaar darcs git
        curl -fsSL --compressed https://git.io/cpm > cpm
        chmod +x cpm
        ./cpm install --show-build-log-on-failure SVN::Core
        echo "PERL5LIB=$PWD/local/perl5:$PERL5LIB" >> "$GITHUB_ENV"
    - name: test
      run: ./misc/author/integration_test.sh
